### ISSUE TITLE
Utility code for ranging windspeeds

### ISSUE THREAD

**Issue by BorisAnthony** [BorisAnthony/Windbarbs#1]
Windbarbs are mapped to wind speeds in increments of 5 Knots as well as Beaufort scale ranges.
e.g.:
```css
.wb-s-20:before,
.wb-r-18-22:before {
  content: "\f004"
}
```

A simple utility class for matching wind speeds to these would be a nice addition (especially since I already have the code in Javascript and PHP elsewhere).
